### ISSUE TITLE
Requests to fetch Ads throws '400 - Bad Request'

### ISSUE THREAD

**Issue by emaillenin** [discoursehosting/discourse-adsense#11]
More details on this [Discourse thread](https://meta.discourse.org/t/google-adsense-plugin-is-now-available/11763/82?u=emaillenin).

Sample URL that throws 400 Bad Request - http://googleads.g.doubleclick.net/pagead/ads?client=ca-3057518829752896&format=1200x90&output=html&h=90&slotname=8324390168&adk=2394456988&w=1200&lmt=1419260729&orig_w=728&flash=16.0.0&url=http%3A%2F%2Fforum.duggout.com%2Ft%2Ftamil-cricket-memes%2F92%2F1&dt=1419260729264&bpp=215&bdt=190543&shv=r20141209&cbv=r20141212&saldr=aa&correlator=123572129793&frm=20&ga_vid=339299047.1412183372&ga_sid=1419260705&ga_hid=1015909997&ga_fc=0&u_tz=330&u_his=5&u_java=1&u_h=1050&u_w=1680&u_ah=1028&u_aw=1676&u_cd=24&u_nplug=12&u_nmime=44&dff=helvetica&dfs=14&adx=238&ady=85&biw=1676&bih=481&eid=33995343%2C317150304&oid=3&rx=0&eae=0&fc=8&brdim=4%2C22%2C4%2C22%2C1676%2C22%2C1676%2C1028%2C1676%2C481&vis=1&abl=CS&ppjl=u&srr=1&fu=0&bc=1&ifi=1&xpc=WfMSdd7rX6&p=http%3A//forum.duggout.com&dtd=481

**Comment by dandv** [comment]
Ugh, I got the same error and spent a bunch of time debugging it.

Please add some trivial code to prefix with "pub-" if necessary.
