### ISSUE TITLE
1.3.0-beta8 plugin incompatibility

### ISSUE THREAD

**Issue by alexharrington** [discoursehosting/discourse-adsense#22]
Please see https://meta.discourse.org/t/upgrade-failed-due-to-adsense-plugin/28671/5

When upgrading to 1.3.0-beta8, there's an error during build which prevents the Discourse instance working.

Fixing the </br> to <br> or <br/> allows Discourse to build but then it only serves a blank white page

**Comment by dcworldwide** [comment]
@alexharrington  Is this still an issue?

**Comment by discoursehosting** [comment]
That was only an issue in 1.3.0-beta8.
