### ISSUE TITLE
Can't enter Adsense pub id on Discourse 1.4 beta

### ISSUE THREAD

**Issue by navjotjsingh** [discoursehosting/discourse-adsense#25]
I try entering my Adsense id(ca-pub-xxxxxxxxxxxxxxxx) in settings and it keeps giving me this error.

    Sorry, an error has occurred.

**Comment by discoursehosting** [comment]
This is too vague. Please rebuild your Discourse instance, make sure your browser cache is refreshed and then provide information from you log files.

**Comment by navjotjsingh** [comment]
I did that. And there is nothing about it in the error logs as well. Except for the fact that the Adsense pub id doesn't get saved.

**Comment by navjotjsingh** [comment]
On further checking, its not just the Adsense id. I cannot save any value. And still nothing in the error logs: http://forum.shopperstalk.in/logs

**Comment by akanimh** [comment]
Same issue here:

![image](https://cloud.githubusercontent.com/assets/3221476/9020429/77fec44a-37c0-11e5-8f4d-d6fabed2f3a5.png)

**Comment by dandv** [comment]
Hey guys, [check for ad blockers](https://github.com/discoursehosting/discourse-adsense/issues/30#issuecomment-186927357).
