### ISSUE TITLE
"Sorry, an error has occurred" and nothing in the logs

### ISSUE THREAD

**Issue by dandv** [discoursehosting/discourse-adsense#30]
This issue keeps recurring - #7, #25, and now in my installation:

![image](https://cloud.githubusercontent.com/assets/33569/13072260/1c9ccb2c-d44d-11e5-88c9-c7eb0a4435c3.png)

Ads functioned fine during a trial period. I then disabled them for a month, and now I can't enable them again. Whenever I check one of the checkboxes to show ads, I get that unhelpful error. Can something be done to expose more about what the actual error is?

I'm running v1.5.0.beta10 +14.

**Comment by discoursehosting** [comment]
This error is a Discourse error, the plugin has nothing to do with it.

**Comment by dandv** [comment]
My point is: how can we *help the user* figure out what the real problem is?

**Comment by discoursehosting** [comment]
Again, this is a generic Discourse error. The site setting being saved does not touch any plugin code.
The user is an admin and he or she should check the logs...

**Comment by dandv** [comment]
I understand; I just don't know how to approach the problem, because there's nothing in `/logs` and I couldn't find [discussion about the inability to save plugin settings](https://meta.discourse.org/search?q=can%27t%20save%20plugin%20setting). Changing other plugin settings at /admin/site_settings/category/plugins works, e.g. "max tags per topic".

So the plugin is completely unaware of why the setting couldn't be saved, and there's no error code to pass through, or exception to catch and display?

Are there other logs I could check?

**Comment by discoursehosting** [comment]
Some topics about site settings can be found by searching meta on the exact error message.
https://meta.discourse.org/t/cant-create-topics-or-edit-site-settings-also-markdown-formatter-is-broken/33499

> So the plugin is completely unaware of why the setting couldn't be saved

Correct.

You might use the F12 toolbar to inspect the response being sent to the browser.

**Comment by dandv** [comment]
Heh, turns out uBlock was causing the error.

> PUT http://2.quantifiedselfforum.com/admin/site_settings/adsense_show_topic_top net::ERR_BLOCKED_BY_CLIENT

Is it worth renaming the paths? adsense -> ad5ense or something more serious.

**Comment by dandv** [comment]
AdBlock causes the same problem.

**Comment by discoursehosting** [comment]
Yes, most adblockers seem to cause this issue.

We're not going to change anything in order to circumvent this. The real solution is to get rid of your adblocker. 

Seriously guys? Running an adblocker while you're trying to place ads on your own forum at the same time?

**Comment by dandv** [comment]
My forum only displays ads to non-logged in users, in order to encourage signups. But yeah, I get the irony.
