### ISSUE TITLE
Can't show only topic top ads

### ISSUE THREAD

**Issue by dandv** [discoursehosting/discourse-adsense#38]
I want to show ads only at the top of topics, but not at the bottom of topics (due to #33) or at top of the topic list.

However, if only the "Show ads on top of the topic" checkbox is checked, no ads are displayed at all. Here is a screencast:

![adsense plugin doesn t show ads on top of topic only](https://cloud.githubusercontent.com/assets/33569/22992628/2bc7ce2e-f375-11e6-9981-b28291ddbbe2.gif)
 
I have to check "Show ads on top of the topic list" as well in order to display topic top ads, but I don't want topic list ads.

**Comment by discoursehosting** [comment]
Thank you for reporting this issue. I have just pushed a fix!
