### ISSUE TITLE
Google Refusing to verify domain for AdSense

### ISSUE THREAD

**Issue by cormip** [discoursehosting/discourse-adsense#40]
The plugin is not generating the specific line of code that Google Adsense is expecting to see in order to validate the site. How can this be fixed? See attached.
![adsense](https://user-images.githubusercontent.com/1108728/131721880-7b7ab324-0ec0-4ca2-b3b9-0c763b4f30b0.png)

**Comment by communiteq** [comment]
This plugin is not being maintained. Please use https://github.com/discourse/discourse-adplugin instead.

**Comment by cormip** [comment]
Switching plugins now. Thanks.
