### ISSUE TITLE
Error when adding pub-id

### ISSUE THREAD

**Issue by haim-ari** [discoursehosting/discourse-adsense#7]
This was tested on 0.9.9.18 and on 1.0.0

![adsense](https://cloud.githubusercontent.com/assets/4179195/4073577/59e721ca-2e96-11e4-8529-eab1f9af5f79.PNG)

**Comment by dandv** [comment]
@imneo1, [check for ad blockers](https://github.com/discoursehosting/discourse-adsense/issues/30#issuecomment-186927357).
